#!/usr/bin/env python3
"""Linux/WSL queue menu backed by the existing experiments.tsv contract.

Windows `.bat` rows use a same-stem `.sh` companion when one exists. Linux-only
experiments and diagnostic gates can instead be registered as native `.sh` rows.
Missing companions are reported, never synthesized here.
"""
from __future__ import annotations

import argparse
import os
import shlex
import sys
from pathlib import Path

import queue_menu as windows_queue

ROOT = windows_queue.ROOT
PLAN = ROOT / "runs" / "_queue_plan.sh"
REQUIRED_COMMON = {
    "run_smoke_check.sh",
    "run_cleanup_checkpoints.sh",
}


def shell_name(batch: str) -> str:
    lowered = batch.lower()
    if lowered.endswith(".bat"):
        return batch[:-4] + ".sh"
    if lowered.endswith(".sh"):
        return batch
    raise ValueError(f"queue entry is neither .bat nor .sh: {batch}")


def with_shell_state(rows, root: Path = ROOT):
    result = []
    for row in rows:
        item = dict(row)
        item["shell_batch"] = shell_name(str(row["batch"]))
        item["shell_exists"] = (root / str(item["shell_batch"])).is_file()
        result.append(item)
    return result


def available(rows):
    # BAT companion rows require both the canonical BAT and its SH adapter.
    # Native SH rows point at the same file in both fields, so this also covers them.
    return [row for row in rows if row["shell_exists"] and row["exists"]]


def _display_rows(rows, warn):
    width = 106
    print("=" * width)
    print("  TinyLM Linux/WSL queue - metadata: experiments.tsv")
    print("=" * width)
    live = available(rows)
    if not live:
        print("  No runnable .sh companion is present.")
    else:
        print(f"  {'id':>3}  {'plan':<7}{'shell entry':<44}{'GPU':<7}{'hours':>7}  note")
        print("  " + "-" * (width - 4))
        for index, row in enumerate(live):
            flags = []
            if row["alone"].upper() == "Y":
                flags.append("alone")
            if row["watch"].upper() == "Y":
                flags.append("watch")
            hours = (
                f"{row['hours_n']:.1f}h"
                if row["hours_n"] >= 1
                else f"{row['hours_n'] * 60:.0f}m"
            )
            flag_text = f"[{'/'.join(flags)}] " if flags else ""
            gpu = windows_queue.GPU_LABEL.get(row["gpu"].upper(), row["gpu"])
            print(
                f"  {index:>3}  {row['plan']:<7}{row['shell_batch']:<44}"
                f"{gpu:<7}{hours:>7}  {flag_text}{row['note']}"
            )
        total = sum(row["hours_n"] for row in live)
        print("  " + "-" * (width - 4))
        print(f"  Total if all are selected: about {total:.1f}h")

    missing = [row for row in rows if not row["shell_exists"]]
    if missing:
        print()
        print("  Unavailable Linux/WSL entries (missing native .sh or BAT companion):")
        for row in missing:
            print(f"    {row['batch']:<46} -> {row['shell_batch']}")
    for item in warn:
        print(f"  [WARN] {item}")
    print()
    print("  Input ids, names, or unique fragments on one line. Empty input cancels.")
    print("=" * width)
    return 0


def _match(available_rows, token: str):
    if token.isdigit() and int(token) < len(available_rows):
        return available_rows[int(token)]

    candidate = Path(token).name
    lowered = candidate.lower()
    if lowered.endswith(".bat"):
        candidate = candidate[:-4] + ".sh"
    elif not lowered.endswith(".sh"):
        candidate += ".sh"
    if not candidate.startswith("run_"):
        candidate = "run_" + candidate

    exact = [
        row
        for row in available_rows
        if row["shell_batch"].lower() == candidate.lower()
        or row["batch"].lower() == token.lower()
    ]
    if len(exact) == 1:
        return exact[0]
    partial = [
        row
        for row in available_rows
        if token.lower() in row["shell_batch"].lower()
        or token.lower() in row["batch"].lower()
    ]
    return partial[0] if len(partial) == 1 else None


def render_plan(chosen) -> str:
    lines = [
        "#!/usr/bin/env bash",
        "# GENERATED by scripts/queue_menu_linux.py. Do not edit.",
        "set -u -o pipefail",
        "",
        'repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"',
        'cd "$repo_root"',
        "",
    ]
    for index, row in enumerate(chosen):
        shell_batch = str(row["shell_batch"])
        if index:
            lines.extend(
                [
                    'printf "\\n[queue] settling 15 s between processes\\n"',
                    "sleep 15",
                ]
            )
        quoted = shlex.quote("./" + shell_batch)
        lines.extend(
            [
                'printf "\\n=================================================================\\n"',
                f"printf '%s\\n' '[queue] starting {shell_batch}'",
                "date",
                "printf '%s\\n' '================================================================='",
                "unset TL_OUTDIR || true",
                f"{quoted}",
                "tl_rc=$?",
            ]
        )
        if shell_batch == "run_smoke_check.sh":
            lines.extend(
                [
                    'if [[ "$tl_rc" -ne 0 ]]; then',
                    "    printf '%s\\n' '[STOP] smoke check failed. Nothing else was run.' >&2",
                    "    exit 3",
                    "fi",
                ]
            )
        else:
            lines.extend(
                [
                    'if [[ "$tl_rc" -ne 0 ]]; then',
                    f"    printf '%s\\n' '[WARN] {shell_batch} returned an error - continuing' >&2",
                    "fi",
                ]
            )
        lines.extend(
            [
                f"printf '%s\\n' '[queue] {shell_batch} done'",
                "date",
                "",
            ]
        )
    lines.extend(["exit 0", ""])
    return "\n".join(lines)


def cmd_build(rows, pick: str) -> int:
    live = available(rows)
    tokens = [item for item in pick.replace(",", " ").split() if item]
    if not tokens:
        print("[queue] empty selection; cancelled.")
        return 2

    chosen = []
    bad = []
    for token in tokens:
        row = _match(live, token)
        if row is None:
            bad.append(token)
        else:
            chosen.append(row)
    for token in bad:
        print(f"[queue] [SKIP] unknown or ambiguous id/name: {token}")
    if not chosen:
        print("[queue] no valid Linux/WSL entry selected.")
        return 2

    print("=" * 100)
    print("  Linux/WSL execution plan")
    print("=" * 100)
    total = 0.0
    for index, row in enumerate(chosen, 1):
        print(f"  {index}. {row['shell_batch']} ({row['plan']}, {row['hours_n']:.1f}h)")
        print(f"     {row['note']}")
        total += row["hours_n"]
    print(f"  Total: about {total:.1f}h")
    if any(row["shell_batch"] == "run_smoke_check.sh" for row in chosen):
        if chosen[0]["shell_batch"] != "run_smoke_check.sh":
            print("  [WARN] smoke is not first.")
    else:
        print("  [WARN] smoke is absent; run it first after code changes.")
    print("=" * 100)

    PLAN.parent.mkdir(parents=True, exist_ok=True)
    PLAN.write_text(render_plan(chosen), encoding="utf-8", newline="\n")
    PLAN.chmod(0o755)
    print(f"[queue] generated {PLAN.relative_to(ROOT)} ({len(chosen)} entries)")
    return 0


def cmd_audit(rows, warn) -> int:
    listed = {str(row["shell_batch"]) for row in rows}
    on_disk = {path.name for path in ROOT.glob("run_*.sh")}
    live_disk = {name for name in on_disk if "-done" not in name} - {"run_queue.sh"}
    errors = 0

    unexpected = sorted(live_disk - listed)
    if unexpected:
        errors += len(unexpected)
        print("[FAIL] .sh entries without an experiments.tsv BAT companion or native SH row:")
        for name in unexpected:
            print(f"  {name}")

    absent_common = sorted(name for name in REQUIRED_COMMON if name not in on_disk)
    if absent_common:
        errors += len(absent_common)
        print("[FAIL] required common WSL entries are absent:")
        for name in absent_common:
            print(f"  {name}")

    missing_companions = sorted(
        str(row["shell_batch"]) for row in rows if not row["shell_exists"]
    )
    if missing_companions:
        print(
            f"[INFO] {len(missing_companions)} rows are unavailable on Linux/WSL; "
            "missing experiment companions are not synthesized."
        )
    for item in warn:
        errors += 1
        print(f"[FAIL] TSV format: {item}")
    print(f"[queue-linux] errors={errors} runnable={len(available(rows))}")
    return errors


def cmd_ids(rows, names) -> int:
    live = available(rows)
    index = {str(row["shell_batch"]): i for i, row in enumerate(live)}
    output = []
    missing = []
    for name in names:
        row = _match(live, name)
        if row is None:
            missing.append(name)
        else:
            output.append((index[str(row["shell_batch"])], row))
    if missing:
        print("[FAIL] not in the Linux/WSL menu: " + ", ".join(missing))
    if output:
        for queue_id, row in output:
            print(f"{queue_id:>4}  {row['shell_batch']}  {row['note']}")
        print("ids: " + " ".join(str(queue_id) for queue_id, _ in output))
    return len(missing)


def main() -> int:
    parser = argparse.ArgumentParser(description="TinyLM Linux/WSL queue menu")
    parser.add_argument("--list", action="store_true")
    parser.add_argument("--build", metavar="IDS")
    parser.add_argument("--audit", action="store_true")
    parser.add_argument("--ids", nargs="+", metavar="ENTRY")
    args = parser.parse_args()

    base_rows, warn = windows_queue.load()
    rows = with_shell_state(base_rows)
    if args.audit:
        return cmd_audit(rows, warn)
    if args.ids:
        return cmd_ids(rows, args.ids)
    if args.build is not None:
        return cmd_build(rows, args.build)
    _ = args.list
    return _display_rows(rows, warn)


if __name__ == "__main__":
    sys.exit(main())
